export const REQUESTED_STREAM_EVENTS = 'REQUESTED_STREAM_EVENTS'
export const REQUESTED_STREAM_EVENTS_SUCCESS = 'REQUESTED_STREAM_EVENTS_SUCCESS'
export const REQUESTED_STREAM_EVENTS_ERROR = 'REQUESTED_STREAM_EVENTS_ERROR'

export const APPLY_FILTER = 'APPLY_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
