export const REQUESTED_STREAM_EVENTS = 'REQUESTED_STREAM_EVENTS'
export const REQUESTED_STREAM_EVENTS_SUCCESS = 'REQUESTED_STREAM_EVENTS_SUCCESS'
export const REQUESTED_STREAM_EVENTS_ERROR = 'REQUESTED_STREAM_EVENTS_ERROR'

export const APPLY_FILTERS = 'APPLY_FILTERS'
export const REMOVE_FILTERS = 'REMOVE_FILTERS'

export const REQUESTED_USER = 'REQUESTED_USER'
export const REQUESTED_USER_SUCCESS = 'REQUESTED_USER_SUCCESS'
export const REQUESTED_USER_ERROR = 'REQUESTED_USER_ERROR'

export const RETRIEVED_GITHUB_REPOS = 'RETRIEVED_GITHUB_REPOS'
